{
  "sksl": {
    "entrypoint": "marker_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float uP1x;\nuniform float uP1y;\nuniform float uP2x;\nuniform float uP2y;\nuniform float uW1;\nuniform float uW2;\nuniform float uColorR;\nuniform float uColorG;\nuniform float uColorB;\nuniform float uColorA;\nuniform float uFlatness;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 p1 = vec2(uP1x, uP1y);\n    vec2 p2 = vec2(uP2x, uP2y);\n    vec2 pa = fragCoord - p1;\n    vec2 ba = p2 - p1;\n    float segLen = length(ba);\n    float t = clamp(dot(pa, ba) / max(segLen * segLen, 0.001000000047497451305389404296875), 0.0, 1.0);\n    float w = mix(uW1, uW2, t);\n    vec2 nearest = p1 + (ba * t);\n    vec2 diff = fragCoord - nearest;\n    vec2 _82;\n    if (segLen > 0.001000000047497451305389404296875)\n    {\n        _82 = ba / vec2(segLen);\n    }\n    else\n    {\n        _82 = vec2(1.0, 0.0);\n    }\n    vec2 dir = _82;\n    vec2 perp = vec2(-dir.y, dir.x);\n    float along = dot(diff, dir);\n    float across = dot(diff, perp);\n    float flatScale = 1.0 + (uFlatness * 1.5);\n    float adjustedDist = length(vec2(along, across * flatScale));\n    float halfW = (w * 0.5) * flatScale;\n    float edge = smoothstep(halfW, halfW - 1.5, adjustedDist);\n    float edgeDark = smoothstep(halfW * 0.300000011920928955078125, halfW, adjustedDist);\n    float darkening = edgeDark * 0.07999999821186065673828125;\n    float alpha = edge * uColorA;\n    float r = uColorR * (1.0 - darkening);\n    float g = uColorG * (1.0 - darkening);\n    float b = uColorB * (1.0 - darkening);\n    fragColor = vec4(r * alpha, g * alpha, b * alpha, alpha);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uP1x",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uP1y",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uP2x",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uP2y",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uW1",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uW2",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 6,
        "name": "uColorR",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 7,
        "name": "uColorG",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 8,
        "name": "uColorB",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 9,
        "name": "uColorA",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 10,
        "name": "uFlatness",
        "rows": 1,
        "type": 10
      }
    ]
  }
}